@extends('layouts.app')
@section('content')

<div class="container-fluid">
    <!-- breadcrumb -->
    <div class="breadcrumb-header justify-content-between">
        <div>
            <h4 class="content-title mb-2">Notice Management !</h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Notice Management</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Notice List</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- /breadcrumb -->
    <!-- main-content-body -->
    <div class="row row-sm">
        <div class="col-md-12 col-xl-12">
            <div class="card overflow-hidden review-project">
                <div class="card-body">
                    <div class="m-4 d-flex justify-content-between">
                        <div id="alert_ajaxx" style="display:none"></div>
                        @if (session('success'))
                        <div class="alert alert-success alert-dismissible fade show w-100" role="alert">
                            {{ session('success') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        @endif
                        <div class="alert alert-success-one alert-dismissible fade show w-100" role="alert" style="display:none">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>

                    <div class="container">
                        <h1>Notices List</h1>
                        <form action="{{ url()->current() }}" method="GET">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Search By Account No." id="account_no" name="account_no" value="{{ request('account_no') }}">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Search By Acknowledgement No." id="ack_no" name="ack_no" value="{{ request('ack_no') }}">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        {{-- <input type="text" class="form-control"  placeholder="Search By Evidence Type"> --}}
                                        <select name="evidence_type" id="evidence_type" class="form-control">
                                            <option value="">--Select By Evidence Type--</option>
                                            @foreach($evidence as $evidence)
                                                <option value="{{$evidence->name}}">{{$evidence->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-3">
                                    <button class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </form>

                        {{-- <table id="noticesTable" class="display">
                            <thead>
                                <tr>
                                    <th>#</th> <!-- Serial number column -->
                                    <th>Notices</th>
                                    <th>Generated By</th>
                                    <th>Actions</th> <!-- Actions column for the View button -->

                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($notices as $index => $notice)
                                    <tr>
                                        <td>{{ $index + 1 }}</td> <!-- Display serial number -->
                                        <td>{{ $notice->notice_type }}</td>
                                        <td>{{ $notice->user->name }}</td>
                                        <td>
                                            <a href="{{ route('notices.show', $notice->id) }}" class="btn btn-primary">View</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table> --}}
                        <table id="noticesTable" class="display d-none">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Notices</th>
                                    <th>Notice Type</th>
                                    <th>Generated By</th>
                                    <th>Actions</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($notices as $index => $notice)
                                    <tr>
                                        <td>{{ $index + 1 }}</td>
                                        <td>{{ $notice->notice_type }}</td>
                                        <td>{{ $notice->type }}</td>
                                        <td>{{ $notice->user->name }}</td>
                                        <td>
                                            <a href="{{ route('notices.show', $notice->id) }}" class="btn btn-primary">View</a>
                                        </td>
                                        <td>
                                        @if($notice->approvedBy)
                                            <div>
                                                <span class="badge bg-success">Approved by {{ @$notice->approvedBy->name }}</span>
                                            </div>
                                        @endif<br>
                                        @if($notice->assingTo)
                                            <div>
                                                <span class="badge bg-danger">Assing to {{ @$notice->assingTo->name }}</span>
                                            </div>
                                        @endif
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- /row -->
</div>
<!-- Include DataTables CSS in the head section -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css">


<!-- Include jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- Include DataTables JS -->
<script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
<!-- Initialize DataTable -->
{{-- <script>
    $(document).ready(function() {
        $('#noticesTable').DataTable();
    });
</script> --}}
<script>
    $(document).ready(function() {
        var table = $('#noticesTable').DataTable({
            responsive: true,
            autoWidth: false
        });

        // Show the table after initialization
        $('#noticesTable').removeClass('d-none');
    });
</script>


@endsection
